version: '3.7'

services:
  web:
    build: .
    ports:
      - 9090:9090
    networks:
      - ionnet
    environment:
    - http://live.geniusclass.co.uk
    - admin@live.geniusclass.co.uk

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
