version: '3.7'

services:
  web:
    build: .
    ports:
      - 9090:9090
    networks:
      - ionnet
    environment:
    - WWW_URL=http://live.geniusclass.co.uk
    - ADMIN_EMAIL=admin@live.geniusclass.co.uk

networks:
  ionnet:
    external: true
    name: ionnet
